// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type NewProfile struct {
	Email       string  `json:"email"`
	Names       string  `json:"names"`
	IDPublic    string  `json:"id_public" bson:"id_public"`
	Birthdate   *string `json:"birthdate"`
	Phone       *string `json:"phone"`
	ProfileType int     `json:"profile_type"`
	Img         *string `json:"img"`
}

type Profile struct {
	ID          string `json:"id"`
	IDPublic    string `json:"id_public" bson:"id_public"`
	ProfileType int    `json:"profile_type"`
	Names       string `json:"names"`
	Email       string `json:"email"`
	Birthdate   string `json:"birthdate"`
	Phone       string `json:"phone"`
	Img         string `json:"img"`
}

type UpdateProfile struct {
	IDPublic    string  `json:"id_public" bson:"id_public"`
	Names       *string `json:"names"`
	Img         *string `json:"img"`
	Email       *string `json:"email"`
	Birthdate   *string `json:"birthdate"`
	Phone       *string `json:"phone"`
	ProfileType *int    `json:"profile_type"`
}
